### ISSUE TITLE
Adding software requirements properties

### ISSUE THREAD

**Issue by chenejac** [vivo-ontologies/vivo-ontology#42]
**What is the motivation for your change request?**
Software might have minimal requirements (processor, memory, free space, dependencies - tomcat, java, RDBMS, OS, etc.)

**Describe the solution you'd like**
A couple of string properties for defining different types of requirements

**Comment by hauschke** [comment]
From https://wiki.lyrasis.org/display/VIVO/2024-09-18+Ontology+Interest+Group+Call:
Decision: the requirements for software like certain OS, required hardware etc. are not relevant for software as a research output or as a tool being described in a RIS. Therefore it is deemed out of scope

@chenejac Can this issue be closed?
