### ISSUE TITLE
Add dc:description to vivo.owl metadata

### ISSUE THREAD

**Issue by hauschke** [vivo-ontologies/vivo-ontology#59]
**What is the motivation for your change request?**
The VIVO Ontology needs more metadata to be FAIR, machine-readable and -actionable. 

This issue was previously contained in https://github.com/vivo-ontologies/vivo-ontology/issues/22

**Describe the solution you'd like**
`<dc:description xml:lang="en">The VIVO Ontology is used to represent the expertise of people engaged in the creation, transmission, and preservation of knowledge and creative works. The VIVO ontology (hereafter referred to as “the ontology”) represents expertise by describing the activities and accomplishments of people in terms of their relationships to particular artifacts of the work, resources they use, institutions that employ them, and other indicators. The ontology is independent of knowledge or creative domain. The ontology supports the identification, evaluation, and impact assessment of individual people and groups of people, as well as identification and reuse of the works of the people.</dc:description>`
**Additional context**
* https://wiki.lyrasis.org/display/VIVO/2024-11-20+Ontology+Interest+Group+Call

**Comment by chenejac** [comment]
@hauschke the end tag is not aligned with start tag - #66. We have to fix this. The validation of the vivo ontology is failing at the moment.
