### ISSUE TITLE
Add doap:repository to vivo.owl metadata

### ISSUE THREAD

**Issue by hauschke** [vivo-ontologies/vivo-ontology#60]
**What is the motivation for your change request?**
The VIVO Ontology needs more metadata to be FAIR, machine-readable and -actionable. 

This issue was previously contained in https://github.com/vivo-ontologies/vivo-ontology/issues/22

**Describe the solution you'd like**
`<doap:repository rdf:resource="https://github.com/vivo-ontologies/vivo-ontology"/>`

**Additional context**
* https://wiki.lyrasis.org/display/VIVO/2024-11-20+Ontology+Interest+Group+Call

**Comment by brianjlowe** [comment]
(As discussed on 04.12 ontology call.) Tatiana points out that Dragan suggested using an instance of a similar repository class instead of the doap:repository datatype property, but this would make it significantly more complicated.  Doing the approach above seems like the best idea for now.
