### ISSUE TITLE
Add doap:bug-database to vivo.owl metadata

### ISSUE THREAD

**Issue by hauschke** [vivo-ontologies/vivo-ontology#61]
**What is the motivation for your change request?**
The VIVO Ontology needs more metadata to be FAIR, machine-readable and -actionable. 

This issue was previously contained in https://github.com/vivo-ontologies/vivo-ontology/issues/22

**Describe the solution you'd like**
`<doap:bug-database rdf:resource="https://github.com/vivo-ontologies/vivo-ontology/issues"/>`

**Additional context**
* https://wiki.lyrasis.org/display/VIVO/2024-11-20+Ontology+Interest+Group+Call

**Comment by brianjlowe** [comment]
Agree this is a good idea on 04.12 ontology call.
